// resources/js/Pages/Auth/Register.vue
<script setup>
import { Head, Link, useForm } from '@inertiajs/vue3';
import AuthenticationCard from '@/Components/AuthenticationCard.vue';
import AuthenticationCardLogo from '@/Components/AuthenticationCardLogo.vue';
import Checkbox from '@/Components/Checkbox.vue';
import InputError from '@/Components/InputError.vue';
import InputLabel from '@/Components/InputLabel.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import TextInput from '@/Components/TextInput.vue';

const form = useForm({
    name: '',
    username: '',
    email: '',
    password: '',
    password_confirmation: '',
    terms: false,
});

const submit = () => {
    form.post(route('register'), {
        onFinish: () => form.reset('password', 'password_confirmation'),
    });
};
</script>

<template>
    <Head title="Register" />

    <AuthenticationCard>
        <template #logo>
            <AuthenticationCardLogo />
        </template>

        <form @submit.prevent="submit">
            <div>
                <InputLabel for="name" value="Name" />
                <TextInput
                    id="name"
                    v-model="form.name"
                    type="text"
                    class="mt-1 block w-full"
                    required
                    autofocus
                    autocomplete="name"
                />
                <InputError class="mt-2" :message="form.errors.name" />
            </div>
            <div>
                <InputLabel for="username" value="Username" />
                <TextInput
                    id="username"
                    v-model="form.username"
                    type="text"
                    class="mt-1 block w-full"
                    required
                    autofocus
                    autocomplete="username"
                />
                <InputError class="mt-2" :message="form.errors.username" />
            </div>

            <div class="mt-4">
                <InputLabel for="email" value="Email" />
                <TextInput
                    id="email"
                    v-model="form.email"
                    type="email"
                    class="mt-1 block w-full"
                    required
                    autocomplete="username"
                />
                <InputError class="mt-2" :message="form.errors.email" />
            </div>

            <div class="mt-4">
                <InputLabel for="password" value="Password" />
                <TextInput
                    id="password"
                    v-model="form.password"
                    type="password"
                    class="mt-1 block w-full"
                    required
                    autocomplete="new-password"
                />
                <InputError class="mt-2" :message="form.errors.password" />
            </div>

            <div class="mt-4">
                <InputLabel for="password_confirmation" value="Confirm Password" />
                <TextInput
                    id="password_confirmation"
                    v-model="form.password_confirmation"
                    type="password"
                    class="mt-1 block w-full"
                    required
                    autocomplete="new-password"
                />
                <InputError class="mt-2" :message="form.errors.password_confirmation" />
            </div>

            <div v-if="$page.props.jetstream.hasTermsAndPrivacyPolicyFeature" class="mt-4">
                <InputLabel for="terms">
                    <div class="flex items-center">
                        <Checkbox id="terms" v-model:checked="form.terms" name="terms" required />

                        <div class="ms-2">
                            I agree to the <a target="_blank" :href="route('terms.show')" class="underline text-sm text-gray-600 hover:text-gray-900 rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">Terms of Service</a> and <a target="_blank" :href="route('policy.show')" class="underline text-sm text-gray-600 hover:text-gray-900 rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">Privacy Policy</a>
                        </div>
                    </div>
                    <InputError class="mt-2" :message="form.errors.terms" />
                </InputLabel>
            </div>

            <div class="flex items-center justify-end mt-4">
                <Link :href="route('login')" class="underline text-sm text-gray-600 hover:text-gray-900 rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                    Already registered?
                </Link>

                <PrimaryButton class="ms-4" :class="{ 'opacity-25': form.processing }" :disabled="form.processing">
                    Register
                </PrimaryButton>
            </div>
        </form>
    </AuthenticationCard>
</template>

// resources/js/Pages/Auth/Register.svelte
<script labg="ts">
    import { inertia, page, useForm } from '@inertiajs/svelte';
    import AuthenticationCard from '@/Components/AuthenticationCard.svelte';
    import AuthenticationCardLogo from '@/Components/AuthenticationCardLogo.svelte';
    import Checkbox from '@/Components/Checkbox.svelte';
    import Helmet from '@/Components/Helmet.svelte';
    import InputError from '@/Components/InputError.svelte';
    import InputLabel from '@/Components/InputLabel.svelte';
    import PrimaryButton from '@/Components/PrimaryButton.svelte';
    import TextInput from '@/Components/TextInput.svelte';

    const form = useForm({
        name: '',
        email: '',
        password: '',
        password_confirmation: '',
        terms: false,
    });

    const submit = () => {
        $form.post('/register', {
            onFinish: () => $form.reset('password', 'password_confirmation'),
        });
    };
</script>

<Helmet title="Register" />

<AuthenticationCard>
    <div slot="logo" class="contents">
        <AuthenticationCardLogo />
    </div>

    <form on:submit|preventDefault={submit}>
        <div>
            <InputLabel forElement="name" value="Name" />
            <TextInput
                id="name"
                bind:value={$form.name}
                type="text"
                classes="mt-1 block w-full"
                required
                autofocus
                autocomplete="name"
            />
            <InputError classes="mt-2" message={$form.errors.name} />
        </div>

        <div class="mt-4">
            <InputLabel forElement="email" value="Email" />
            <TextInput
                id="email"
                bind:value={$form.email}
                type="email"
                classes="mt-1 block w-full"
                required
                autocomplete="username"
            />
            <InputError classes="mt-2" message={$form.errors.email} />
        </div>

        <div class="mt-4">
            <InputLabel forElement="password" value="Password" />
            <TextInput
                id="password"
                bind:value={$form.password}
                type="password"
                classes="mt-1 block w-full"
                required
                autocomplete="new-password"
            />
            <InputError classes="mt-2" message={$form.errors.password} />
        </div>

        <div class="mt-4">
            <InputLabel forElement="password_confirmation" value="Confirm Password" />
            <TextInput
                id="password_confirmation"
                bind:value={$form.password_confirmation}
                type="password"
                classes="mt-1 block w-full"
                required
                autocomplete="new-password"
            />
            <InputError classes="mt-2" message={$form.errors.password_confirmation} />
        </div>

        {#if $page.props.jetstream.hasTermsAndPrivacyPolicyFeature}
            <div class="mt-4">
                <InputLabel forElement="terms">
                    <div class="flex items-center">
                        <Checkbox id="terms" bind:checked={$form.terms} required />

                        <div class="ms-2">
                            I agree to the
                            <a
                                target="_blank"
                                href="/terms-of-service"
                                use:inertia
                                class="rounded-md text-sm text-gray-600 underline hover:text-gray-900 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
                            >
                                Terms of Service
                            </a>
                            and
                            <a
                                target="_blank"
                                href="/privacy-policy"
                                use:inertia
                                class="rounded-md text-sm text-gray-600 underline hover:text-gray-900 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
                            >
                                Privacy Policy
                            </a>
                        </div>
                    </div>
                    <InputError classes="mt-2" message={$form.errors.terms} />
                </InputLabel>
            </div>
        {/if}

        <div class="mt-4 flex items-center justify-end">
            <a
                href="/login"
                use:inertia
                class="rounded-md text-sm text-gray-600 underline hover:text-gray-900 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
            >
                Already registered?
            </a>

            <PrimaryButton classes="ms-4" disabled={$form.processing}>Register</PrimaryButton>
        </div>
    </form>
</AuthenticationCard>
